name: Homeglance
version: "0.1.0-alpha.70"

slug: homeglance
description: Modern, mobile-first dashboard for Home Assistant. No YAML, no compromise.
url: "https://github.com/Ivkaiv/homeglance"
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: auto
host_network: false
ports:
  3040/tcp: 3040
ports_description:
  3040/tcp: Homeglance Web UI
panel_icon: mdi:view-dashboard-variant
panel_title: Homeglance
panel_admin: false
homeassistant_api: true
hassio_api: false
ingress: true
ingress_port: 3040
image: ghcr.io/ivkaiv/{arch}-homeglance
